import re

def tag_sentence(sentence):
    # Splitting the sentence into tokens while keeping delimiters
    tokens = re.split(r"(\s+|[\"'])", sentence)
    
    # Initialize variables
    output_tokens = []
    output_labels = []
    in_single_quotes = False
    in_double_quotes = False
    start_single_quote = False
    start_double_quote = False
    
    # Iterate over each token
    for token in tokens:
        if token == "'":
            if in_single_quotes:
                in_single_quotes = False  # Closing single quote
            else:
                in_single_quotes = True
                start_single_quote = True  # Starting new contact name
            continue

        if token == '"':
            if in_double_quotes:
                in_double_quotes = False  # Closing double quote
            else:
                in_double_quotes = True
                start_double_quote = True  # Starting new text content
            continue

        if token.strip():  # Avoiding whitespace
            if in_single_quotes:
                if start_single_quote:
                    output_labels.append('O')
                    start_single_quote = False
                else:
                    output_labels.append('O')
            elif in_double_quotes:
                if start_double_quote:
                    output_labels.append('O')
                    start_double_quote = False
                else:
                    output_labels.append('O')
            else:
                output_labels.append('O')
            output_tokens.append(token)

    return output_tokens, output_labels

def make_data(sentence_list, list_name, output_file):
    with open(output_file, 'a') as f:
        for sentence in sentence_list:
            tokens, labels = tag_sentence(sentence)
            formatted_sentence = ' '.join(tokens)
            formatted_labels = ' '.join(labels)
            f.write(f"BOS {formatted_sentence} EOS\tO {formatted_labels} {list_name}\n")
        f.write("\n")

increase_music_volume_queries = [
    "turn up the music",
    "make the music louder",
    "boost the music volume",
    "increase the music level",
    "please turn up the tunes",
    "raise the music by '15'",
    "up the music volume by 'ten'",
    "amplify the music sound",
    "crank up the music",
    "elevate the music volume",
    "pump up the jams by '20'",
    "turn the music up by 'five'",
    "enhance the music volume",
    "turn up the music by 'thirty'",
    "up the tunes",
    "make the music play louder by 'ten'",
    "please increase the music by '5'",
    "bump up the music volume"
]

decrease_music_volume_queries = [
    "turn down the music",
    "make the music quieter",
    "lower the music volume",
    "decrease the music level",
    "please turn down the tunes",
    "reduce the music volume by '15'",
    "down the music volume by 'ten'",
    "soften the music sound",
    "decrease the music to '50'",
    "quiet the music",
    "diminish the music volume",
    "bring down the music by '20'",
    "turn the music down by 'five'",
    "lessen the music volume",
    "turn down the music by 'thirty'",
    "reduce the tunes",
    "make the music play softer by 'ten'",
    "please decrease the music by '5'",
    "drop the music volume"
]

set_music_volume_queries = [
    "set the music volume to '40'",
    "please set the music to 'five'",
    "adjust the music to '25'",
    "music at '20'",
    "set the tunes to '30'",
    "set the music level to 'fifteen'",
    "change the music to 'ten'",
    "set the sound to 'fifty'",
    "music volume at '60'",
    "adjust the tunes to '35'",
    "please set music at '75'",
    "set the music volume to 'forty five'",
    "set the sound level to '55'",
    "change the music volume to '65'",
    "music should be '70'",
    "please set the tunes to '80'",
    "set the volume of music to '90'",
    "music volume at '85'",
    "set the music to '100'",
    "please adjust the music to '95'"
]


increase_volume_queries = [
    "please increase the volume",
    "please up the volume by '15'",
    "please raise the volume by 'ten'",
    "turn up the volume",
    "make the volume louder",
    "boost the volume",
    "increase the volume level",
    "please turn up the sound",
    "raise the volume by '20'",
    "turn up the volume by 'five'",
    "please boost the volume by 'thirty'",
    "make the volume go up",
    "turn the volume up by '75'",
    "increase the sound level",
    "please raise the sound",
    "up the volume by 'ten'",
    "please turn the volume up by '5'",
    "make the sound louder by 'forty'",
    "increase the audio volume"
]
decrease_volume_queries = [
    "please decrease the volume",
    "please lower the volume by '15'",
    "please reduce the volume by 'ten'",
    "turn down the volume",
    "make the volume quieter",
    "reduce the volume",
    "decrease the volume level",
    "please turn down the sound",
    "lower the volume by '20'",
    "turn down the volume by 'five'",
    "please reduce the volume by 'thirty'",
    "make the volume go down",
    "decrease the sound level",
    "please lower the sound",
    "drop the volume by 'ten'",
    "please turn the volume down by '5'",
    "make the sound quieter by 'forty'",
    "decrease the audio volume"
]

set_volume_queries = [
    "please set the volume to '40'",
    "set the volume to 'five'",
    "could you set the volume to '25'",
    "volume to '20'",
    "adjust the volume to '30'",
    "set the volume level to '15'",
    "please change the volume to 'ten'",
    "set the sound to '50'",
    "volume at 'sixty'",
    "set audio to '35'",
    "please set volume at '75'",
    "adjust the volume to '45'",
    "set the sound level to '55'",
    "change the volume to '65'",
    "volume should be '70'",
    "please set the audio to '80'",
    "set volume to 'ninety'",
    "volume at 'eighty five'",
    "set the volume to 'one hundred'",
    "please adjust the volume to '95'"
]


start_surgery_queries = [
    "begin the surgery",
    "start the operation",
    "initiate the surgical procedure",
    "commence the surgery",
    "kick off the operation",
    "proceed with the surgery",
    "open up for surgery",
    "launch the surgical process",
    "get the surgery underway",
    "embark on the surgical procedure",
    "move forward with the surgery",
    "trigger the operation",
    "activate the surgical process",
    "begin the surgical intervention",
    "set the surgery in motion",
    "get the operation started",
    "proceed to start surgery",
    "start the medical procedure",
    "initiate the operation",
    "open the surgical procedure"
]

surgery_complete_queries = [
    "surgery is complete",
    "operation is finished",
    "surgical procedure is done",
    "surgery has concluded",
    "operation has ended",
    "surgery is over",
    "surgical process is complete",
    "procedure is finished",
    "surgery has been completed",
    "operation has been finalized",
    "surgery is finalized",
    "surgical procedure is over",
    "surgery has been concluded",
    "operation is done",
    "surgical intervention is complete",
    "surgery is wrapped up",
    "procedure has ended",
    "operation is complete",
    "surgical process has concluded",
    "surgery has finished"
]

patient_in_queries = [
    "patient is in",
    "patient has arrived",
    "patient is here",
    "patient is ready",
    "patient is present",
    "patient has been admitted",
    "patient is in the room",
    "patient is in place",
    "patient is positioned",
    "patient is settled",
    "patient is on the table",
    "patient is in position",
    "patient has been brought in",
    "patient is in the operating room",
    "patient has been prepped",
    "patient is on site",
    "patient is checked in",
    "patient is set up",
    "patient has entered",
    "patient is on the bed"
]

patient_out_queries = [
    "patient is out",
    "patient has left",
    "patient is discharged",
    "patient has been released",
    "patient is no longer here",
    "patient is gone",
    "patient has exited",
    "patient is out of the room",
    "patient has been moved out",
    "patient is no longer in",
    "patient has been transferred out",
    "patient is out of the operating room",
    "patient has been taken out",
    "patient is no longer present",
    "patient has been relocated",
    "patient is out of the building",
    "patient has departed",
    "patient is out of the facility",
    "patient has been removed",
    "patient is off the table"
]


sentences = [
    "send a text message to 'ethan epp' saying \"happy birthday i hope it is a good one\"",
    "can you text 'dr. ming yao' and say \"the patient is ready for you in operating room one\"",
    "text 'carol soo' that \"the list of medical information was very useful thank you\"",
    "please message 'alex kim' and tell them \"your appointment is scheduled for next Wednesday at 3 pm\"",
    "notify 'jordan casey' that \"the meeting has been rescheduled to Friday morning\"",
    "ask 'sam lee' if \"he could bring the documents to the office tomorrow\"",
    "remind 'priya gupta' to \"submit the annual report by end of this week\"",
    "inform 'lucas wright' that \"his car needs to be picked up from the service center by 5 pm\"",
    "let 'mia chen' know \"we will meet at the usual spot for lunch\"",
    "tell 'olivia jensen' that \"i have left the keys under the doormat\"",
    "message 'sarah miller' to say \"the dinner plans are confirmed for 7 pm at our place\"",
    "send 'tom reed' a reminder \"to bring the team jerseys on Sunday\"",
    "could you inform 'natalie brown' that \"her prescription is ready for pickup\"",
    "please let 'marco bianchi' know \"we need to finalize the project proposal by Monday\"",
    "ask 'ella morris' if \"she has received the shipment from last week\"",
    "remind 'mohammed ali' that \"the conference call is at noon tomorrow\"",
    "tell 'sophie lee' that \"we need her expertise on the new tech release\"",
    "let 'henry clark' know \"the documents are ready for his review\"",
    "message 'chloe koh' to confirm \"her flight details have been updated as requested\"",
    "inform 'peter parker' that \"the book he ordered has arrived at the store\"",
    "please remind 'lisa monroe' that \"the school fundraiser starts at eight tonight\"",
    "ask 'rithvik gupta' if \"he can attend the workshop next Thursday\"",
    "tell 'amanda lin' to \"bring her laptop to the client meeting tomorrow\"",
    "notify 'kevin smith' that \"the system upgrade is scheduled for 10 pm tonight\"",
    "message 'diana prince' about \"the changes in the conference agenda\"",
    "send 'bruce black' a note \"to check the latest security updates\"",
    "can you inform 'clark graham' that \"the new shipment includes the items he requested\"",
    "remind 'steve do' to \"update the training manual with the recent changes\"",
    "tell 'amy jensen' that \"the project review has been moved to next Monday\"",
    "ask 'tyson jackson' if \"she has the files ready for tomorrow's presentation\"",
    "message 'brady lee' to say \"your order will be ready for pickup at 4 pm\"",
    "notify 'shojiro johnson' that \"her consultation time has been changed to 2 pm tomorrow\"",
    "tell 'matt dean' that \"the team needs his final decision on the marketing strategy\"",
    "ask 'grace po' if \"she can extend her trip to handle additional meetings\"",
    "remind 'frank nguyen' that \"he has a rehearsal scheduled at six o'clock\"",
    "inform 'marie sabet' that \"the laboratory equipment will be delivered next Tuesday\"",
    "let 'neil smith' know \"the team awaits his feedback on the project blueprint\"",
    "send 'emily bronte' a reminder \"to review the manuscript by this Friday\"",
    "message 'walter jackson' to confirm \"the meeting time at 10 am is still suitable for him\"",
    "please tell 'rachel greise' that \"we've booked her a flight for the upcoming business trip\"",
    "notify 'ross yellum' that \"the document he requested is now available in the shared folder\"",
    "inform 'monica phipps' that \"the ingredients she ordered are out of stock\"",
    "ask 'natalia bing' if \"he could confirm his attendance at the retreat next month\"",
    "remind 'daya martin' to \"bring his script and costume to the theater today\"",
    "tell 'phoebe iver' that \"her application has been approved and she should contact the office\"",
    "let 'lena huang' know \"the revised proposal has major improvements over the first draft\"",
    "message 'joshua ross' to say \"the family gathering has been rescheduled to next Saturday\"",
    "send 'vito martinez' a reminder \"to renew his membership at the club before the end of the month\"",
    "could you inform 'pablo mencino' that \"his presence is required at the board meeting on Monday\""
]

just_names = [
    "can you text 'jackie'",
    "please text 'james'",
    "i would like you to message 'jacob medrano'",
    "can you message 'lauren liu'",
    "please text 'josephine'",
    "could you send a message to 'emily'",
    "can you text 'michael'",
    "please message 'olivia parker'",
    "send a text to 'ethan smith'",
    "i need you to text 'sarah lee'",
    "could you message 'david jones'",
    "please text 'amelia chen'",
    "send a message to 'noah wilson'",
    "can you text 'mia wang'",
    "message 'benjamin clark' please",
    "i need you to text 'charlotte king'",
    "can you send a message to 'liam taylor'",
    "please message 'sophia moore'",
    "text 'lucas white' for me",
    "send a text to 'harper brown'"
]

removal_requests = [
    "delete the part of my text that says \"what time is dinner\"",
    "remove the content from the text that says \"i love you\" please",
    "delete the phrase \"see you soon\"",
    "remove the words \"thank you for everything\"",
    "delete the sentence \"i will call you later\"",
    "remove the section that says \"let s meet at eight\"",
    "delete the line \"i can t make it tomorrow\"",
    "remove the text \"happy birthday to you\"",
    "delete from the message \"sorry for the late reply\"",
    "remove the part that says \"can we reschedule\"",
    "delete the phrase \"i m not sure about this\"",
    "remove the words \"good night and sweet dreams\"",
    "delete the sentence \"i ve attached the files below\"",
    "remove the section that says \"looking forward to our meeting\"",
    "delete the line \"please confirm your attendance\"",
    "remove the text \"i need more time to think about it\"",
    "delete from the message \"let s catch up soon\"",
    "remove the part that says \"this is just a reminder\"",
    "delete the phrase \"i hope this helps\"",
    "remove the words \"see you tomorrow\""
]

zoom = [
    "can you call 'amelia johnson'",
    "please call 'noah thompson'",
    "i would like you to start a Zoom call with 'emma lopez'",
    "can you start a Zoom call with 'liam gonzalez'",
    "please call 'olivia martinez'",
    "could you call 'william hernandez'",
    "can you start a Zoom call with 'ava jackson'",
    "please start a Zoom call with 'james davis'",
    "call 'isabella white' for me",
    "i need you to call 'lucas harris'",
    "could you start a Zoom call with 'mia martin'",
    "please call 'benjamin clark'",
    "start a Zoom call with 'charlotte lewis'",
    "can you call 'mason allen'",
    "please start a Zoom call with 'sophia young'",
    "i would like you to call 'ethan hall'",
    "can you start a Zoom call with 'harper scott'",
    "please call 'michael king'",
    "call 'elizabeth wright' for me",
    "start a Zoom call with 'daniel lee'"
]
zoom_add_queries = [
    "add 'john wright' to the call",
    "include 'emma davis' in the call",
    "please add 'michael brown' to the call",
    "bring 'olivia smith' into the call",
    "can you add 'liam johnson' to the call",
    "invite 'sophia white' to join the call",
    "add 'james martin' into the call",
    "could you add 'krish agarwall' to the call",
    "please bring 'benjamin lee' into the call",
    "include 'ava wilson' on the call",
    "add 'lucas clark' to our call",
    "invite 'mia young' into the call",
    "can you bring 'ethan king' into the call",
    "please add 'isabelle nguyen' to the call",
    "add 'benjamin soo' to this call",
    "include 'charlotte green' in our call",
    "could you please add 'daniel adams' to the call",
    "bring 'harper baker' into this call",
    "invite 'henry hill' to the call",
    "add 'ella evans' to the meeting",
    "can you add 'jackson hall' to our call",
    "include 'abigail roberts' on this call",
    "please bring 'sebastian turner' into the meeting",
    "add 'emily nelson' to our meeting",
    "could you include 'jackson carter' in the call",
    "invite 'zoe mitchell' to join the meeting",
    "add 'oliver perez' into this call",
    "bring 'scarlett rogers' to the call",
    "please add 'mason edwards' to our call"
]

google_search_commands = [
    "can you look up \"usd to euro conversion\" on google",
    "google \"california mug recall\"",
    "can you search up \"road closures in california\"",
    "please google \"weather forecast for new york\"",
    "search online for \"how to make a chocolate cake\"",
    "can you find \"nearest gas station\" on google",
    "google \"symptoms of flu\"",
    "could you please search up \"movie times near me\" please",
    "can you check \"stock prices for apple inc\" on google",
    "please look up \"who is the president of france\" online",
    "google \"directions to the nearest airport\"",
    "search for \"best sushi restaurants nearby\"",
    "can you find \"how to tie a tie\" on google",
    "google \"what year did the titanic sink\"",
    "can you please search up \"tips for job interviews\"",
    "please google \"upcoming solar eclipses\"",
    "search online \"translate hello to spanish\"",
    "can you find \"calories in a banana\" on google",
    "google \"world's tallest building\"",
    "search up \"how long to boil an egg\"",
    "can you look up \"public holidays in 2024\" on google",
    "google \"who invented the telephone\" for me",
    "can you search up \"current time in tokyo\" please",
    "please google \"how many countries in the world\"",
    "search on google for \"best laptops 2024\"",
    "can you find \"vegan restaurants near me\" on google",
    "google \"top 10 universities in the world\"",
    "search up \"dog parks nearby\"",
    "can you check \"latest cricket scores\" on google",
    "please look up \"international space station viewing times\" on google",
    "google \"how to apply for a passport\"",
    "search for \"what is bitcoin\"",
    "can you find \"diy home decor ideas\" online",
    "google \"distance to mars\"",
    "can you search up \"what is quantum computing\"",
    "please google \"olympic records in swimming\"",
    "search on google for \"local election dates\"",
    "can you find \"best books of 2024\" on google",
    "google \"how to change a tire\"",
    "search up \"deep sea creatures\"",
    "what's the \"usd to yen conversion\"",
    "find out \"how many ounces in a pound\"",
    "tell me \"the capital of canada\"",
    "look up \"age of the universe\"",
    "search \"who wrote Hamlet\"",
    "find out \"the speed of light\"",
    "tell me \"who won the last world cup\" right now",
    "look up \"average human walking speed\"",
    "search \"how many stars in the milky way\"",
    "check \"what languages are spoken in south africa\"",
    "find out \"how to start a business\"",
    "tell me \"who discovered penicillin\"",
    "look up \"symptoms of dehydration\"",
    "search \"next olympic games host city\"",
    "check \"how to make homemade pizza\"",
    "what's the \"usd to yen conversion\"",
    "find out \"how many ounces in a pound\"",
    "tell me \"the capital of canada\"",
    "look up \"age of the universe\"",
    "search \"who wrote Hamlet\"",
    "check \"current world population\"",
    "discover \"life expectancy in the united states\"",
    "explore \"causes of the french revolution\"",
    "find out \"the speed of light\"",
    "tell me \"who won the last world cup\"",
    "look up \"average human walking speed\"",
    "search \"how many stars in the milky way\"",
    "check \"what languages are spoken in south africa\"",
    "discover \"top grossing movies of all time\"",
    "explore \"longest river in the world\"",
    "find out \"how to start a business\" please",
    "tell me \"who discovered penicillin\"",
    "look up \"symptoms of dehydration\"",
    "search \"next olympic games host city\"",
    "check \"how to make homemade pizza\" for me please"
]

youtube_video_search_commands = [
    "please look up the \"fast and furious three trailer\" on youtube",
    "youtube video of \"seal spinning in circles\"",
    "look up the \"dancing cat\" video",
    "can you bring up a video on \"how to identify skin cancer\" please",
    "\"killers of the flower moon trailer\" on youtube",
    "search on youtube for \"easy vegan recipes\"",
    "can you find the video \"best goals of the 2022 world cup\"",
    "youtube video on \"how to fix a flat tire\"",
    "look up the \"sunrise timelapse\" video",
    "please bring up a video on \"meditation for beginners\"",
    "youtube video of \"funny dog compilation\"",
    "search the \"top ten sci-fi movies\" on youtube",
    "can you find the video \"live street music performances\"",
    "look up the \"tutorial on using photoshop\" video",
    "please bring up a video on \"history of the roman empire\"",
    "youtube video of \"what is quantum computing\"",
    "search on youtube for \"best smartphones in 2023\"",
    "can you find the video \"deep sea mysteries\"",
    "look up the \"yoga for back pain\" video",
    "please bring up a video on \"building a wooden table\"",
    "search on youtube for \"beginner guitar lessons\"",
    "can you find the video \"tips for first-time home buyers\"",
    "youtube video on \"how to make homemade ice cream\"",
    "look up the \"complete guide to knitting\" video",
    "please bring up a video on \"basic first aid techniques\"",
    "youtube video of \"street magic tricks revealed\"",
    "search the \"highlights of the 2024 olympics\" on youtube",
    "can you find the video \"how to start a podcast\"",
    "look up the \"best hikes in south america\" video",
    "please bring up a video on \"learning french for beginners\"",
    "youtube video of \"planet earth from space\"",
    "search on youtube for \"interview with a famous author\"",
    "can you find the video \"wildlife in the amazon rainforest\"",
    "look up the \"how to decorate a small apartment\" video",
    "please bring up a video on \"the science of sleep\"",
    "youtube video of \"urban gardening ideas\"",
    "search the \"best indie games 2023\" on youtube",
    "can you find the video \"how to brew your own beer\"",
    "look up the \"DIY home decor projects\" video",
    "please bring up a video on \"effective public speaking tips\"",
    "please look up the \"fast and furious three trailer\" on youtube",
    "youtube video of \"seal spinning in circles\"",
    "look up the \"dancing cat\" video",
    "can you bring up a video on \"how to identify skin cancer\" please",
    "\"killers of the flower moon trailer\" on youtube",
    "search on youtube for \"easy vegan recipes\"",
    "can you find the video \"best goals of the 2022 world cup\"",
    "youtube video on \"how to fix a flat tire\"",
    "look up the \"sunrise timelapse\" video",
    "please bring up a video on \"meditation for beginners\"",
    "youtube video of \"funny dog compilation\"",
    "search the \"top ten sci-fi movies\" on youtube",
    "can you find the video \"live street music performances\"",
    "look up the \"tutorial on using photoshop\" video",
    "please bring up a video on \"history of the roman empire\"",
    "youtube video of \"what is quantum computing\"",
    "search on youtube for \"best smartphones in 2023\"",
    "can you find the video \"deep sea mysteries\"",
    "look up the \"yoga for back pain\" video",
    "please bring up a video on \"building a wooden table\"",
    "can you show me a video about \"how to play chess\" on youtube",
    "find a video called \"best hiking trails in California\"",
    "youtube search for \"how to start a blog\"",
    "can you pull up the \"learn French for beginners\" video",
    "find on youtube \"DIY home decor ideas\"",
    "can you retrieve the video \"guide to digital photography\"",
    "search youtube for \"street food around the world\"",
    "please show me a video about \"repairing a smartphone screen\"",
    "find the \"live jazz music concerts\" video",
    "youtube search for \"tips for healthy eating\"",
]

window_enlargement_commands = [
    "enlarge the 'web browser' window",
    "make the 'zoom' window larger",
    "enlarge the 'preferences card app' window",
    "increase the size of the 'data analyzer' window",
    "expand the 'cloud manager' window",
    "make the 'project tracker' window bigger",
    "grow the 'note keeper' window",
    "increase the window size of 'email organizer'",
    "enlarge the 'task scheduler' window",
    "make the 'budget planner' window larger",
    "expand the 'creative studio' window",
    "grow the 'health monitor' app window",
    "increase the size of the 'travel guide' window",
    "enlarge the 'recipe book' window",
    "make the 'fitness tracker' window bigger",
    "expand the 'family calendar' window",
    "grow the 'home security' window",
    "increase the window size of 'music player'",
    "enlarge the 'video editor' window",
    "make the 'learning portal' window larger"
]

window_minimization_commands = [
    "minimize the 'web browser' window",
    "make the 'zoom' window smaller",
    "reduce the size of the 'preferences card app' window",
    "shrink the 'data analyzer' window",
    "minimize the 'cloud manager' window",
    "please make the 'project tracker' window smaller",
    "reduce the 'note keeper' window",
    "could you shrink the 'email organizer' window",
    "minimize the 'task scheduler' window",
    "can you make the 'budget planner' window smaller please",
    "reduce the size of the 'creative studio' window",
    "shrink the 'health monitor' app window please",
    "minimize the 'travel guide' window",
    "make the 'recipe book' window smaller",
    "reduce the 'fitness tracker' window",
    "could you please shrink the 'family calendar' window",
    "minimize the 'home security' window",
    "make the 'music player' window smaller",
    "please reduce the size of the 'video editor' window",
    "could you shrink the 'learning portal' window"
]


temperature_queries = [
    "what is the room temperature",
    "what is the temperature in the room",
    "what does the sensor say the temperature is in the room right now",
    "can you tell me the current room temperature",
    "please check the room temperature",
    "what s the temperature inside the room at the moment",
    "could you find out the temperature in the room",
    "how warm is the room right now",
    "what temperature is it in here",
    "check the temperature in this room",
    "what s the reading on the room s temperature gauge",
    "tell me the room s current temperature",
    "could you let me know the temperature in here",
    "what does the thermostat read right now",
    "how cold is it in this room at the moment",
    "give me the temperature reading for this room",
    "what s the current temp in the room",
    "can you find the temperature in this room for me",
    "what s the temperature here",
    "check what the temperature sensor is showing",
    "make the 'zoom' window smaller",
    "close down the 'preferences card app' window a bit",
    "downsize the 'data analyzer' window",
    "minimize the 'cloud manager' window",
    "make the 'project tracker' window less large",
    "lessen the size of the 'note keeper' window",
    "downsize the 'email organizer' window",
]

humidity_queries = [
    "what is the humidity level in the room",
    "what is the humidity level",
    "what does the sensor say the humidity is in the room right now",
    "please tell me the humidity level in the room",
    "can you check the room s humidity level for me",
    "what s the current humidity in this room",
    "could you tell me the humidity level inside the room",
    "i need to know the humidity level in the room",
    "check the humidity level and let me know",
    "what is the humidity reading for the room",
    "could you find out the current humidity in the room",
    "how humid is it in here right now",
    "what does the humidity gauge read at the moment",
    "tell me what the humidity level is right now",
    "can you provide the current room humidity",
    "what s the humidity situation in the room at the moment",
    "please give me the humidity reading in this room",
    "i m wondering what the humidity is in the room right now",
    "could you check what the humidity sensor says",
    "what s the recorded humidity level in this space"
]

smoke_level_queries = [
    "what are the smoke levels in the room",
    "check the smoke levels currently",
    "can you give me the smoke level reading",
    "i need the current smoke level in here",
    "please report the smoke concentration in the room",
    "how high is the smoke level in this room",
    "tell me the smoke level here",
    "report on the smoke density in the room",
    "is the smoke level high in here right now",
    "provide the reading of smoke levels",
    "what does the smoke detector read",
    "can you find out the smoke levels here",
    "i would like to know the smoke levels in this space",
    "how much smoke is detected in the room",
    "check and report the smoke levels",
    "give me an update on the smoke levels in this area",
    "what is the smoke status in the room",
    "can you monitor and report the smoke density",
    "what s the measurement of smoke in the room",
    "i m curious about the smoke levels right now"
]

schedule_queries = [
    "show the 'room' schedule",
    "show 'my' schedule",
    "show 'dr smith' s schedule",
    "show the 'first patient' scheduled",
    "when is 'my' next patient",
    "what does 'dr johnson' have going on today",
    "can you bring up 'dr soo' s itinerary for the day",
    "display 'team alpha' s schedule for the week",
    "what on the agenda for 'conference room b' today",
    "show 'nurse miller' s shift schedule",
    "when is the next 'surgery' scheduled",
    "can you show 'mr green' s meeting times",
    "what time is 'sarah' s presentation today",
    "bring up 'the marketing department' s calendar",
    "when is 'the ceo' s next available slot",
    "show the 'guest lecturer' s timetable",
    "can you display 'professor thompson' s class schedule",
    "what appointments does 'counselor lee' have today",
    "bring up 'the third floor conference room' s bookings",
    "can you find out when 'janet' s training session is"
]

dicom_schedule_queries = [
    "open dicom schedule",
    "who is in my schedule",
    "tell me who is in schedule",
    "list all patients scheduled today",
    "show dicom schedule",
    "display today's schedule",
    "who is on my schedule",
    "show me today's patient schedule",
    "open the schedule for today",
    "who is listed in my schedule",
    "provide the dicom schedule",
    "list today's scheduled patients",
    "who is scheduled today",
    "give me the dicom schedule",
    "who are the patients in the schedule",
    "show all scheduled patients for today",
    "what is today's patient schedule",
    "who is in the schedule today",
    "list patients in today's schedule",
    "show me the dicom schedule"
]
first_patient_schedule_queries = [
    "show first patient scheduled",
    "who is the first patient scheduled",
    "display the first patient in the schedule",
    "show me the first patient scheduled",
    "who is scheduled first",
    "reveal the first patient in the schedule",
    "list the first patient scheduled",
    "who is the first patient on the schedule",
    "show the first patient on the schedule",
    "tell me the first patient scheduled",
    "who is the first patient today",
    "give me the first patient scheduled",
    "who is at the top of the schedule",
    "show the first patient for today",
    "identify the first patient scheduled",
    "who is the initial patient scheduled",
    "display the first patient for today",
    "list the first patient on today's schedule",
    "show me the initial patient scheduled",
    "who is first on the schedule today"
]

last_patient_schedule_queries = [
    "who is the last patient on the schedule",
    "tell me the final patient scheduled",
    "who is the last one scheduled today",
    "list the final patient in today's schedule",
    "show me the last patient on today's schedule",
    "who is the last patient listed",
    "give me the name of the last patient scheduled",
    "who is at the end of today's schedule",
    "tell me who is the final patient today",
    "who is the last patient on the docket",
    "identify the last patient scheduled today",
    "who is the final person on today's schedule",
    "show the last patient for today",
    "who is the last individual scheduled",
    "who is the final patient on the list",
    "who is the last entry in today's schedule",
    "give me the last patient on the schedule",
    "tell me the last patient for today",
    "who is the last patient in the schedule",
    "list the last patient scheduled"
]



next_patient_schedule_queries = [
    "who is the next patient",
    "tell me the next patient on the list",
    "show me the next scheduled patient",
    "who is up next on the schedule",
    "who is the next patient to see",
    "who is the next on the patient schedule",
    "next patient in line",
    "who is the upcoming patient",
    "show the next patient in schedule",
    "who do i see next",
    "who is the next patient on today's schedule",
    "who is the next person scheduled",
    "next patient to be seen",
    "who is next in the schedule",
    "who is the next patient for today",
    "who comes after the current patient",
    "who is scheduled next",
    "who is the next appointment",
    "next patient scheduled",
    "upcoming patient in schedule"
]
end_call_queries = [
    "end the call",
    "hang up the phone",
    "disconnect the call",
    "finish the call",
    "close the zoom meeting",
    "end the video call",
    "wrap up the call",
    "end the meeting",
    "hang up",
    "stop the call",
    "exit the call",
    "log off the zoom meeting",
    "cut off the call",
    "conclude the conversation",
    "sign off the call",
    "finish the zoom call",
    "end the voice call",
    "disconnect the zoom call"
]

mute_mic_queries = [
    "mute the microphone",
    "turn off the mic please",
    "silence the microphone",
    "mute my mic",
    "mute the audio input",
    "deactivate the mic please",
    "mute the mic",
    "disable the microphone",
    "mute my microphone",
    "mute the input sound please",
    "mute the mic now",
    "switch off the mic",
    "shut off the microphone",
    "mute audio input",
    "turn off the microphone",
    "stop the mic",
    "silence my microphone",
    "mute the sound input",
    "mute me please",
    "can you mute me",
    "can you please mute my microphone",
    "please mute my microphone",
    "mute my microphone please",
]
unmute_mic_queries = [
    "unmute the microphone",
    "turn on the mic",
    "unmute my mic",
    "please unmute the microphone",
    "can you unmute the mic",
    "unmute the mic",
    "activate the microphone",
    "turn on the microphone",
    "please unmute my microphone",
    "can you turn on the mic",
    "enable the mic",
    "unmute my microphone",
    "turn the mic back on",
    "unmute audio input",
    "can you unmute my mic",
    "please unmute the mic",
    "switch on the microphone",
    "turn the microphone on",
    "please turn on the mic",
    "can you enable the microphone"
]

start_video_queries = [
    "start the video",
    "turn on the camera",
    "activate the video",
    "enable the camera",
    "please start the video",
    "can you turn on the video",
    "start my camera",
    "turn on my video",
    "enable video",
    "begin video",
    "please activate the camera",
    "can you start the video",
    "turn the camera on",
    "switch on the video",
    "start the webcam",
    "turn on my webcam",
    "begin the video feed",
    "enable my camera",
    "please turn on the camera"
]

stop_video_queries = [
    "stop the video",
    "turn off the camera",
    "disable the video",
    "turn off the video",
    "stop my camera",
    "deactivate the video",
    "please stop the video",
    "can you turn off the camera",
    "end the video",
    "switch off the camera",
    "stop the webcam",
    "turn my video off",
    "please disable the camera",
    "can you stop the video",
    "stop the camera feed",
    "turn off the webcam",
    "deactivate my video",
    "please turn off the video",
    "stop video now"
]

stop_speaking_queries = [
    "stop speaking",
    "please stop talking",
    "stop",
    "cancel",
    "quiet",
    "halt your speech",
    "stop talking now",
    "can you stop speaking",
    "please stop",
    "silence",
    "cancel speech",
    "stop the voice",
    "end talking",
    "please be quiet",
    "please stop your voice",
    "cease speaking",
    "cancel",
    "stop speaking"
]

cancel_all_timers_queries = [
    "cancel all timers",
    "delete all timers",
    "clear all timers",
    "remove all timers",
    "stop all timers",
    "erase all timers",
    "reset all timers",
    "please cancel all timers",
    "can you delete all timers",
    "cancel every timer",
    "delete every timer",
    "stop every timer",
    "clear every timer",
    "remove every timer",
    "cancel all active timers",
    "delete all active timers",
    "clear all active timers",
    "please clear all timers",
    "can you cancel all timers",
    "erase every timer"
]

time_left_on_named_timer_queries = [
    "how much time is left on my 'baking' timer",
    "'surgery' timer time remaining",
    "how much time remains on the 'exercise' timer",
    "what s the remaining time on my 'reading' timer",
    "check the 'dirty laundry' timer time",
    "time left on the 'hourly medication' timer",
    "how long is left on the 'cooking' timer",
    "remaining time on the 'meeting' timer",
    "how much time left on 'study' timer",
    "what s left on the 'workout' timer",
    "how much time on my 'presentation' timer",
    "can you check the 'gardening' timer",
    "how much longer on the 'cleaning' timer",
    "time remaining on the 'homework' timer",
    "how much time is on the 'yoga' timer",
    "what s the time left on 'practice' timer",
    "check remaining time on 'writing' timer",
    "how much time left on the 'project' timer",
    "how long is left on my 'driving' timer",
    "what s the time remaining on the 'study break' timer"
]
remaining_timers_queries = [
    "how many timers are set",
    "what timers are set",
    "tell me about the remaining timers",
    "how much time is left on all timers",
    "list all active timers",
    "give me the status of all timers",
    "what are the current timers",
    "please tell me the remaining timers",
    "can you tell me how many timers are set",
    "show all active timers",
    "how much time do the timers have left",
    "what is the time left on all timers",
    "provide details on all timers",
    "can you list all timers",
    "what timers are currently set",
    "tell me the status of each timer",
    "how many timers are running",
    "give me the countdowns on all timers",
    "what are the details of all timers",
    "how much time is left on each timer"
]
show_all_timers_queries = [
    "show all timers",
    "display all timers",
    "what are the active timers",
    "can you show all timers",
    "please display the timers",
    "show me all timers",
    "show the timers",
    "display the active timers",
    "can you display all timers",
    "reveal all timers",
    "please show me the timers",
    "show all active timers",
    "display all current timers",
    "please show the active timers",
    "show the current timers",
    "display my timers"
]
reset_all_timers_queries = [
    "reset all timers",
    "restart all timers",
    "reinitialize all timers",
    "can you reset all timers",
    "please restart all timers",
    "reset every timer",
    "restart every timer",
    "reset all active timers",
    "please reset all timers",
    "can you restart all timers",
    "reinitialize every timer",
    "reset the timers",
    "restart all the timers",
    "please reset the timers",
    "can you reset the timers",
    "reset every active timer",
    "restart all current timers",
    "reset all running timers",
    "please restart every timer",
    "reinitialize all active timers"
]
hide_all_timers_queries = [
    "hide all timers",
    "conceal all timers",
    "please hide all timers",
    "can you conceal all timers",
    "hide every timer",
    "hide all the timers",
    "can you hide every timer",
    "please conceal the timers",
    "make all timers invisible",
    "hide the active timers",
    "conceal each timer",
    "hide every timer from view",
    "please hide the timers",
    "can you put away all timers",
    "remove every timer from display",
    "hide all current timers",
    "please make all timers invisible",
    "conceal all the timers"
]
collect_diagnostic_logs_queries = [
    "collect diagnostic logs",
    "gather the diagnostic logs",
    "retrieve all diagnostic logs",
    "please collect the diagnostic logs",
    "can you gather diagnostic logs",
    "get the diagnostic logs",
    "please collect system diagnostic logs",
    "fetch the diagnostic logs",
    "collect all diagnostic data",
    "gather system logs",
    "please retrieve diagnostic logs",
    "please can you collect all diagnostic logs",
    "collect the logs",
    "please gather all diagnostic information",
    "retrieve diagnostic data",
    "could you please collect system logs",
    "fetch all diagnostic logs for me please",
    "please gather the diagnostic logs",
    "can you retrieve the diagnostic logs",
    "collect all logs now"
]
collect_diagnostic_logs_usb_queries = [
    "collect diagnostic logs on usb",
    "gather diagnostic logs to usb",
    "fetch diagnostic logs onto usb",
    "please collect diagnostic logs on usb for me",
    "please can you gather diagnostic logs to usb",
    "collect diagnostic logs onto usb drive",
    "retrieve diagnostic logs on usb",
    "collect system logs to usb",
    "get diagnostic logs on usb please",
    "please gather the diagnostic logs on usb",
    "can you fetch diagnostic logs onto usb",
    "collect the diagnostic logs on usb",
    "collect logs for diagnostics on usb",
    "gather system logs to usb",
    "please collect all system logs on usb",
    "retrieve all diagnostic logs to usb",
    "collect the logs onto usb",
    "please collect system logs on usb",
    "can you retrieve diagnostic logs onto usb",
    "pleasefetch all diagnostic logs to usb"
]

resetting_tourniquet_queries = [
    "reset the tourniquet",
    "restart the tourniquet",
    "reinitialize the tourniquet",
    "initialize the tourniquet again",
    "reset tourniquet settings",
    "reboot the tourniquet",
    "reset the tourniquet device",
    "reconfigure the tourniquet",
    "clear and reset the tourniquet",
    "reset tourniquet function",
    "reinitiate the tourniquet",
    "reset the tourniquet mechanism",
    "reboot tourniquet system",
    "restart tourniquet operation",
    "reset the tourniquet control",
    "reinitialize tourniquet function",
    "reset the tourniquet process",
    "restart the tourniquet procedure",
    "initialize tourniquet from scratch",
    "reset and start tourniquet"
]

showing_tourniquet_queries = [
    "show the tourniquet",
    "display the tourniquet",
    "reveal the tourniquet",
    "bring up the tourniquet",
    "make the tourniquet visible",
    "present the tourniquet",
    "show tourniquet information",
    "display tourniquet status",
    "reveal tourniquet details",
    "bring up tourniquet data",
    "make the tourniquet appear",
    "show the tourniquet device",
    "display the tourniquet settings",
    "reveal the tourniquet screen",
    "bring the tourniquet into view",
    "show the current tourniquet",
    "display the tourniquet control",
    "reveal the active tourniquet",
    "bring up the current tourniquet",
    "make the tourniquet screen visible"
]

hiding_tourniquet_queries = [
    "hide the tourniquet",
    "conceal the tourniquet",
    "remove the tourniquet display",
    "take down the tourniquet",
    "make the tourniquet invisible",
    "hide tourniquet information",
    "conceal tourniquet status",
    "remove tourniquet details",
    "take down tourniquet data",
    "make the tourniquet disappear",
    "hide the tourniquet device",
    "conceal the tourniquet settings",
    "remove the tourniquet screen",
    "take the tourniquet out of view",
    "hide the current tourniquet",
    "conceal the tourniquet control",
    "remove the active tourniquet",
    "take down the current tourniquet",
    "make the tourniquet screen disappear",
    "hide the tourniquet interface"
]

asking_tourniquet_time_queries = [
    "how long has the tourniquet been up",
    "what is the tourniquet duration",
    "how much time has the tourniquet been on",
    "how long has the tourniquet been applied",
    "what is the elapsed time for the tourniquet",
    "how much time has the tourniquet been active",
    "how long has the tourniquet been in place",
    "what is the tourniquet application time",
    "how long has the tourniquet been used",
    "what is the tourniquet on time",
    "how much time has passed since the tourniquet was applied",
    "how long has the tourniquet been deployed",
    "what is the duration of the tourniquet",
    "how much time has the tourniquet been in use",
    "how long has the tourniquet been functioning",
    "what is the tourniquet engagement time",
    "how much time has the tourniquet been up for",
    "how long has the tourniquet been in operation",
    "what is the total time for the tourniquet",
    "how long has the tourniquet been activated"
]

extend_tourniquet_queries = [
    "extend the tourniquet by 'five minutes'",
    "add '10 minutes' to the tourniquet time",
    "increase tourniquet time by '15 minutes'",
    "prolong the tourniquet duration by 'twenty minutes'",
    "extend tourniquet application by '25 minutes'",
    "lengthen the tourniquet use by 'thirty minutes'",
    "add '35 minutes' to the tourniquet duration",
    "increase the tourniquet period by '40 minutes'",
    "extend tourniquet deployment by '45 minutes'",
    "prolong the use of the tourniquet by '50 minutes'",
    "lengthen the application of the tourniquet by '55 minutes'",
    "add 'an hour' to the tourniquet application time",
    "increase the time of the tourniquet by '65 minutes'",
    "extend the tourniquet activation by 'seventy minutes'",
    "prolong the tourniquet engagement by '75 minutes'",
    "add '80 minutes' to the tourniquet use",
    "increase tourniquet application period by '85 minutes'",
    "lengthen the tourniquet engagement by '90 minutes'",
    "extend the time the tourniquet is up by 'ninety minutes'",
    "add '100 minutes' to the tourniquet duration"
]

joint_commands = [
    "turn up the music 'and' start a 20 minute timer for my break 'then' check humidity levels",
    "please decrease the volume 'and also' set a reminder to call mom",
    "patient is in 'then' set a timer for 30 minutes called blood",
    "begin the surgery 'and then' notify me when it s complete",
    "could you please raise the volume by 10 'and' send a text to john saying i will be late",
    "please set the music volume to 50 'then' start a timer for 15 minutes named exercise",
    "start the operation 'and' play some background music",
    "turn down the volume 'then' set a reminder for the meeting at 2 pm",
    "please set the volume to 40 'and' start a 10 minute timer called break",
    "raise the music by 15 'and also' start a timer for 25 minutes for studying",
    "make the music louder 'then' remind me to take a break in 30 minutes 'then' google how long should i stretch for during the work day",
    "increase the volume level 'and' text joanna and tell her the movie is about to start",
    "please turn down the sound 'then' send an email to the team about the meeting",
    "lower the volume by 20 'and' start a timer for 10 minutes for the laundry",
    "up the volume by ten 'then' start playign music by the beatles 'and then' notify me when the timer for 45 minutes is up",
    "begin the surgical procedure 'and also' play some calming music",
    "proceed with the surgery 'then' send a message to the family about the progress",
    "turn up the music by five 'then' set an alarm for tomorrow morning at 7 am 'and' please raise the volume 'and' start a 15 minute timer for my presentation",
    "decrease the music volume 'and also' remind me to check the oven in 20 minutes 'and then' open spotify",
    "start a zoom call with john 'and then' mute my mic",
    "set the volume to zero 'and' text joanna and tell her the movie is about to start",
    "please boost the volume by thirty 'and' start a 30 minute timer named yoga",
    "patient is in 'and' start a 30 minute timer called operation 'then' start a zoom call with dr ming yao",
    "increase the audio volume 'then' send a message to alex about the meeting",
    "turn down the music by five 'and' set an alarm for my workout in the morning 'then' activate the stopwatch",
    "please set the music to 75 'and' remind me to water the plants in 15 minutes 'and' delete all my timers",
    "adjust the volume to 30 'then' send a text to emma saying i will be late please 'then' google how far the drive from san jose to la is",
    "please turn up the music 'and also' set a timer for 20 minutes for the oven",
    "lower the volume by ten 'then' start a timer for 10 minutes for a break",
    "make the music play louder by ten 'and' set an alarm for the meeting at 3 pm",
    "increase the sound level 'then' send a message to the team about the progress",
    "turn down the volume 'and also' remind me to check the laundry in 15 minutes 'then' open the zoom app",
    "please set the volume level to 15 'and' start a 10 minute timer for a break",
    "raise the volume by 20 'then' set a reminder to call mom in 30 minutes",
    "up the tunes 'and' notify me when the timer for 30 minutes is up",
    "please lower the volume by 15 'then' send an email to the team about the meeting",
    "increase the music level 'and also' remind me to take a break in 20 minutes",
    "make the volume louder 'then' start a 25 minute timer named exercise",
    "turn up the music 'and' start a 15 minute timer for my workout",
    "please set the music volume to 25 'then' send a text to john saying i will be late 'and then' play some background music 'and' begin the surgery now",
    "set the volume to 20 'then' start a 10 minute timer called meeting",
    "please lower the music 'and also' remind me to check the mail in 15 minutes",
    "raise the volume by 30 'then' send a message to david about the progress please",
    "increase the volume 'and' start a 20 minute timer for cooking",
    "could you please turn down the music by five 'then' set a reminder to call dad",
    "please boost the volume by 25 'and' start a timer for 45 minutes named yoga",
    "adjust the music to 35 'then' send a text to sarah saying i will be late",
    "please set the music to 60 'and' remind me to check the oven in 20 minutes",
    "lower the volume by 20 'then' start a 15 minute timer for a break",
    "make the music louder by five 'and' set an alarm for tomorrow morning at 8 am",
    "increase the volume level by ten 'and also' start a timer for 25 minutes for studying 'and then' send a message to david about the progress please",
    "turn up the music by twenty 'then' remind me to take a break in 30 minutes",
    "please set the volume to 50 'and' start a 20 minute timer for exercise",
    "lower the volume by thirty 'then' send an email to the team about the meeting",
    "raise the music by five 'and' start a 10 minute timer called workout",
    "increase the sound level by ten 'then' set a reminder to call mom in 30 minutes 'then' log me out",
    "please turn down the music 'and' start a 15 minute timer for my presentation",
    "adjust the volume to 45 'then' send a text to emma saying i will be late",
    "please raise the volume by twenty 'and also' set a timer for 20 minutes for the oven 'and then' open the browser winder",
    "make the music louder 'and then' start a 25 minute timer named study",
    "turn down the volume 'then' set an alarm for my workout in the morning",
    "please set the music volume to 70 'and' remind me to water the plants in 15 minutes 'then' delete all my timers",
    "increase the audio volume 'then' send a message to alex about the meeting",
    "lower the volume by twenty 'and' start a timer for 10 minutes for the laundry 'then' activate the stopwatch",
    "please boost the volume by fifteen 'then' notify me when the timer for 45 minutes is up",
    "could you please check the humidity levels 'then' check the temperature 'and then' check the particulate levels",
    "can you check the particulate levels in the room 'and then' google what are safe particulate levels for an operating room"
]


unknown_command_phrases = [
    "can you turn on the lights in the room",
    "please switch on the lights",
    "activate the lights in here",
    "turn on the lights for me",
    "schedule a meeting with Dr. Smith for tomorrow",
    "set up an appointment with joe bondi for tomorrow",
    "please book a meeting with my wife next week",
    "organize a meeting with Dr. Smith for tomorrow",
    "what s the battery status of the device",
    "check the device s battery level",
    "how much battery does the device have",
    "tell me the battery status",
    "find the nearest hospital for me",
    "locate the closest hospital",
    "where is the nearest hospital",
    "show me the nearest hospital",
    "update the patient s record with today s notes",
    "add today s notes to the patient record",
    "enter today s details in the patient s file",
    "update the patient record with today s information",
    "record the patient s vitals now",
    "take the patient s vitals",
    "measure the patient s vital signs",
    "log the patient s vitals",
    "navigate to 123 Main Street",
    "take me to my house",
    "find a route to disneyland",
    "turn off the air conditioner",
    "switch off the air conditioner",
    "please deactivate the air conditioner",
    "adjust the thermostat to 72 degrees",
    "set the thermostat to 72 degrees",
    "turn the thermostat to 72 degrees",
    "list the patient s medications",
    "show me the patient s medication list",
    "what medications is the patient on",
    "provide the patient s medications",
    "send an email to Dr. Johnson",
    "compose an email to Dr. Johnson",
    "email Dr. Johnson",
    "write an email to Dr. Johnson",
    "order more medical supplies",
    "restock medical supplies",
    "purchase more medical supplies",
    "reorder medical supplies",
    "check the patient s blood pressure",
    "measure the patient s blood pressure",
    "take a blood pressure reading for the patient",
    "get the patient s blood pressure",
    "measure the heart rate of the patient",
    "take the patient s heart rate",
    "record the patient s heart rate",
    "begin preparations for the surgery",
    "start surgery preparations",
    "prep for the surgery",
    "get ready for the surgery",
    "clean the operating room",
    "sterilize the operating room",
    "sanitize the operating room",
    "prepare the operating room for the next surgery",
    "activate the emergency protocol",
    "initiate the emergency protocol",
    "start the emergency protocol",
    "trigger the emergency protocol",
    "sync with the fitness tracker",
    "connect to the fitness tracker",
    "pair with the fitness tracker",
    "synchronize with the fitness tracker",
    "provide an update on the patient s status",
    "give a status update on the patient",
    "tell me the patient s current status",
    "generate a medical report for the patient",
    "produce a medical report for the patient",
    "draft a medical report for the patient",
    "turn on voice control",
    "activate voice control",
    "enable voice control",
    "start voice control",
    "schedule a follow-up appointment",
    "set up a follow-up appointment",
    "book a follow-up appointment",
    "organize a follow-up appointment",
    "assign a nurse to the patient",
    "allocate a nurse to the patient",
    "designate a nurse to the patient",
    "ask for the patient s medical history",
    "get the patient s medical history",
    "retrieve the patient s medical history",
    "verify the identity of the patient",
    "confirm the patient s identity",
    "check the patient s identity",
    "validate the patient s identity",
    "enable privacy mode",
    "turn on privacy mode",
    "activate privacy mode",
    "start privacy mode",
    "turn on the operating lights",
    "switch on the operating lights",
    "turn up the operating lights",
    "alert security to the operating room",
    "notify security about the operating room",
    "summon security to the operating room",
    "start the patient transfer process",
    "initiate the patient transfer",
    "begin the patient transfer",
    "transfer the patient",
    "call the next patient to the examination room",
    "bring the next patient in",
    "invite the next patient to the exam room",
    "fetch the next patient for examination",
    "track the patient s progress",
    "monitor the patient s progress",
    "keep track of the patient s progress",
    "follow the patient s progress",
    "document the surgery notes",
    "record the surgery notes",
    "write down the surgery notes",
    "log the surgery notes",
    "activate the cleaning protocol",
    "start the cleaning protocol",
    "initiate the cleaning protocol",
    "trigger the cleaning protocol",
    "record the surgery procedure",
    "log the surgery procedure",
    "document the surgery procedure",
    "write down the surgery procedure",
    "start a physiotherapy session",
    "begin a physiotherapy session",
    "initiate a physiotherapy session",
    "commence a physiotherapy session",
    "set up a remote consultation with Dr. Lee",
    "activate patient monitoring",
    "start patient monitoring",
    "enable patient monitoring",
    "turn on patient monitoring",
    "review the patient s lab results",
    "examine the patient s lab results",
    "check the patient s oxygen levels",
    "measure the patient s oxygen levels",
    "get the patient s oxygen levels",
    "record the patient s oxygen levels",
    "enter the patient into the system",
    "revise the surgery protocols",
    "modify the surgery protocols",
    "change the surgery protocols"
]

open_ended_questions = [
    "how do you make a pizza",
    "what are good vacation destinations for December if I want to see lots of cool lights",
    "why did the economy crash in 2008",
    "can you tell me a story",
    "list the best albums from every year between 1995 and 2005",
    "how does the internet work",
    "what are the key differences between classical and quantum physics",
    "describe the process of photosynthesis",
    "what are some popular myths and legends",
    "how does a car engine function",
    "explain the history of the Roman Empire",
    "what are the fundamental principles of democracy",
    "how do airplanes stay in the air",
    "what are the main causes of climate change",
    "could you describe the journey of a drop of water through the water cycle",
    "how does blockchain technology work",
    "what are the different types of renewable energy sources",
    "could you explain the significance of the theory of relativity",
    "how does the human brain process information",
    "what are some important cultural practices around the world",
    "how do you play chess",
    "what are the stages of human development from birth to adulthood",
    "how does the electoral process work in the United States",
    "what are the benefits and challenges of space exploration",
    "describe the evolution of the English language",
    "could you explain how vaccines work",
    "what are the principles of modern architecture",
    "how has the role of women in society changed over time",
    "could you tell me about some famous works of art and their significance",
    "how do different cultures celebrate the New Year",
    "what are the basic components of a computer",
    "describe the process of making wine",
    "what are the major religions of the world",
    "how do plants adapt to their environment",
    "what are the effects of globalization",
    "how does the financial market operate",
    "what are the characteristics of a healthy diet",
    "could you describe the process of making a film",
    "how do different species of animals communicate",
    "what are the key elements of a successful business strategy",
    "how does the immune system protect the body",
    "what are the historical causes and impacts of World War II",
    "how do different ecosystems function",
    "what are some effective techniques for learning a new language",
    "how has technology changed the way we communicate",
    "could you tell me about the benefits of meditation and mindfulness",
    "how do authors develop their writing style",
    "what are the ethical considerations in artificial intelligence",
    "how does music influence emotions",
    "could you describe the structure and function of DNA",
    "how do antibiotics work",
    "what are the different types of vaccines",
    "could you explain the process of organ transplantation",
    "how does chemotherapy treat cancer",
    "what are the symptoms of diabetes",
    "how do you perform CPR",
    "what is the significance of blood types",
    "can you describe the stages of Alzheimer's disease",
    "what are the causes of heart disease",
    "how do you manage chronic pain",
    "could you explain the role of genetics in disease",
    "how does the body heal after surgery",
    "what are the benefits of physical therapy",
    "how does the digestive system work",
    "what are the latest advancements in medical technology",
    "how do you treat a broken bone",
    "what are the common symptoms of a stroke",
    "can you describe the process of dialysis",
    "what are the different types of mental health disorders",
    "how do vaccines protect against diseases",
    "could you explain the importance of prenatal care",
    "how do you manage high blood pressure",
    "what are the side effects of common medications",
    "how does the respiratory system function",
    "what are the risk factors for cancer",
    "how do you diagnose and treat allergies",
    "can you explain the process of in vitro fertilization",
    "what are the signs and symptoms of depression",
    "how do you maintain a healthy lifestyle",
    "what are the different types of surgical procedures"
]


make_data(open_ended_questions, "open_ended", "output.txt")
# make_data(showing_tourniquet_queries, "show_tourniquet", "output.txt")
# make_data(hiding_tourniquet_queries, "hide_tourniquet", "output.txt")
# make_data(asking_tourniquet_time_queries, "duration_tourniquet", "output.txt")
# make_data(hide_all_timers_queries, "hide_all_timers", "output.txt")
# make_data(next_patient_schedule_queries, "next_patient", "output.txt")