name: Update Requirements and Run Tests

on: [push]

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.14

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev ffmpeg

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download spacy model
      run: |
        python -m spacy download en_core_web_sm

    - name: Run tests
      run: |
        pytest

    - name: Update requirements.txt
      run: |
        pip freeze > requirements.txt

    - name: Commit changes
      if: success()  # Only commit if tests pass
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add requirements.txt
        git commit -m "Update requirements.txt"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
